### PR TITLE
Make SourceKit-LSP build without warnings

### PR DESCRIPTION
**Pull request by ahoppen**
Fixes all build warnings in SourceKit-LSP so that it builds without any issues using recent Swift development snapshots (`swift-DEVELOPMENT-SNAPSHOT-2024-07-22-a` and `swift-6.0-DEVELOPMENT-SNAPSHOT-2024-07-24-a`)

### CODE REVIEW

**Review by bnbarham — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/swiftlang/indexstore-db/pull/218

@swift-ci Please test Linux

**Comment by ahoppen** [comment]
https://github.com/swiftlang/indexstore-db/pull/218

@swift-ci Please test macOS

**Comment by benrimmington** [comment]
@ahoppen Linux builds are failing, I think due to the removal of `@preconcurrency import` in this pull request.

* <https://ci.swift.org/job/swift-PR-Linux-smoke-test/14372/>
* <https://ci.swift.org/job/swift-PR-Linux-smoke-test/14373/>
* <https://ci.swift.org/job/swift-PR-Linux-smoke-test/14374/>
* <https://ci.swift.org/job/swift-PR-Linux-smoke-test/14375/>

```
/home/build-user/sourcekit-lsp/Sources/SourceKitLSP/Rename.swift:625:40: error: type 'Symbol' does not conform to the 'Sendable' protocol
 623 |         )
 624 |       } else {
 625 |         logger.debug("Not translating \(definitionSymbol) to Swift because it is not referenced from Swift")
     |                                        `- error: type 'Symbol' does not conform to the 'Sendable' protocol
 626 |         swiftName = nil
 627 |       }

/home/build-user/indexstore-db/Sources/IndexStoreDB/Symbol.swift:55:15: note: struct 'Symbol' does not conform to the 'Sendable' protocol
 53 | }
 54 | 
 55 | public struct Symbol: Hashable {
    |               `- note: struct 'Symbol' does not conform to the 'Sendable' protocol
 56 | 
 57 |   public var usr: String

/home/build-user/sourcekit-lsp/Sources/SourceKitLSP/Rename.swift:13:1: warning: add '@preconcurrency' to treat 'Sendable'-related errors from module 'IndexStoreDB' as warnings
  11 | //===----------------------------------------------------------------------===//
  12 | 
  13 | import IndexStoreDB
     | `- warning: add '@preconcurrency' to treat 'Sendable'-related errors from module 'IndexStoreDB' as warnings
  14 | import LanguageServerProtocol
  15 | import SKLogging
```

**Comment by bnbarham** [comment]
https://github.com/swiftlang/indexstore-db/pull/218 wasn't merged simultaneously, it's in now so this should be fixed.
